export const CART_ACTION_TYPES = {
  TOGGLE_CART_OPEN: "cart/TOGGLE_CART_OPEN",
  SET_CART_ITEMs: "cart/SET_CART_ITEM",
  SET_CART_TOTAL: "cart/SET_CART_TOTAL",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
};
